server:
  port: 7012

spring:
  datasource:
    url: jdbc:mysql://192.168.17.111:3306/gmall_activity?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    host: 192.168.17.111
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
  redis:
    port: 6379
    host: 192.168.17.111
    database: 0



