server:
  port: 7002
feign:
  client:
    config:
      default:
        readTimeout: 300000
        connecTimeout: 300000
#  hystrix:
spring:
  redis:
    host: 192.168.17.111
    port: 6379
    database: 0
