server:
  port: 7004
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.1:8848
      config:
        server-addr: 192.168.17.1:8848
  redis:
    host: 192.168.17.111
    port: 6379
    database: 0
  elasticsearch:
    rest:
      uris: http://192.168.17.111:9200
feign:
  client:
    config:
      default:
        readTimeout: 300000
        connecTimeout: 300000
